name: Pull Request Check Up

on: [pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Notify Step Status
      if: always()
      uses: stegzilla/discord-notify@v2
      with:
        webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
        title: "Step Status: ${{ job.status }}"
        message: "${{ job.name }}: ${{ job.status }}"
        include_image: false
        avatar_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
        username: Mantis Github Protector

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.3

    - name: Golangci-lint and Complexity
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.51.2
        args: --print-issued-lines=false --exclude-use-default=false --fix --timeout=3m

    - name: Unit Test
      run: go test $(go list ./... | grep -v /mocks/) --race -v -short -coverprofile=profile.cov

    - name: Build
      run: go build -v ./...